// Copyright (c) 2025. Battelle Energy Alliance, LLC
// ALL RIGHTS RESERVED

#include "instructions.h"

#include <binaryninjaapi.h>
#include <gtest/gtest.h>

#include <string>
#include <vector>

constexpr uint32_t TEST_DATA = 0xFFFFFFFF;

/**
 * GenerateTestOpcodes creates a vector of tuples <opcode, instr. name>.
 * In cases where the opcode encodes data in fields (e.g. a shift value or a
 * constant value) we inject fake data into the opcode to ensure the decoder
 * properly ignores any part of the opcode except the defined bits.
 *
 * Injecting test data that is longer than required (e.g. full uint8 when we
 * only need 4 bits) also verifies that the SetX methods for the instructions
 * properly truncate data when necessary.
 *
 * @return vector of tuples <opcode, expected instr. name>
 */
std::vector<std::tuple<unsigned int, std::string, TIC28X::ObjectMode>>
GenerateTestOpcodes() {
  std::vector<std::tuple<unsigned int, std::string, TIC28X::ObjectMode>>
      opcodes = {
          {0xFFFFFFFF, "NULLOPT", TIC28X::OBJMODE_ANY},
          {TIC28X::Aborti::opcode, TIC28X::Aborti::full_name,
           TIC28X::Aborti::objmode},
          {TIC28X::AbsAcc::opcode, TIC28X::AbsAcc::full_name,
           TIC28X::AbsAcc::objmode},
          {TIC28X::AbstcAcc::opcode, TIC28X::AbstcAcc::full_name,
           TIC28X::AbstcAcc::objmode},
          {TIC28X::AddAccConst16Shift::SetConst16(TEST_DATA) |
               TIC28X::AddAccConst16Shift::SetShift(TEST_DATA),
           TIC28X::AddAccConst16Shift::full_name,
           TIC28X::AddAccConst16Shift::objmode},
          {TIC28X::AddAccLoc16ShiftT::SetLoc16(TEST_DATA),
           TIC28X::AddAccLoc16ShiftT::full_name,
           TIC28X::AddAccLoc16ShiftT::objmode},
          {TIC28X::AddAccLoc16::SetLoc16(TEST_DATA),
           TIC28X::AddAccLoc16::full_name, TIC28X::AddAccLoc16::objmode},
          {TIC28X::AddAccLoc16Shift1_15::SetLoc16(TEST_DATA) |
               TIC28X::AddAccLoc16Shift1_15::SetShift(TEST_DATA),
           TIC28X::AddAccLoc16Shift1_15::full_name,
           TIC28X::AddAccLoc16Shift1_15::objmode},
          {TIC28X::AddAccLoc16Shift16::SetLoc16(TEST_DATA),
           TIC28X::AddAccLoc16Shift16::full_name,
           TIC28X::AddAccLoc16Shift16::objmode},
          {TIC28X::AddAccLoc16Shift0_15::SetLoc16(TEST_DATA) |
               TIC28X::AddAccLoc16Shift0_15::SetShift(TEST_DATA),
           TIC28X::AddAccLoc16Shift0_15::full_name,
           TIC28X::AddAccLoc16Shift0_15::objmode},
          {TIC28X::AddAxLoc16::SetLoc16(TEST_DATA) |
               TIC28X::AddAxLoc16::SetRegAx(TEST_DATA),
           TIC28X::AddAxLoc16::full_name, TIC28X::AddAxLoc16::objmode},
          {TIC28X::AddLoc16Ax::SetLoc16(TEST_DATA) |
               TIC28X::AddLoc16Ax::SetRegAx(TEST_DATA),
           TIC28X::AddLoc16Ax::full_name, TIC28X::AddLoc16Ax::objmode},
          {TIC28X::AddLoc16Const16::SetLoc16(TEST_DATA) |
               TIC28X::AddLoc16Const16::SetConst16(TEST_DATA),
           TIC28X::AddLoc16Const16::full_name,
           TIC28X::AddLoc16Const16::objmode},
          {TIC28X::AddbAccConst8::SetConst8(TEST_DATA),
           TIC28X::AddbAccConst8::full_name, TIC28X::AddbAccConst8::objmode},
          {TIC28X::AddbAxConst8::SetRegAx(TEST_DATA) |
               TIC28X::AddbAxConst8::SetConst8(TEST_DATA),
           TIC28X::AddbAxConst8::full_name, TIC28X::AddbAxConst8::objmode},
          {TIC28X::AddbSpConst7::SetConst7(TEST_DATA),
           TIC28X::AddbSpConst7::full_name, TIC28X::AddbSpConst7::objmode},
          {TIC28X::AddbXarnConst7::SetRegN(TEST_DATA) |
               TIC28X::AddbXarnConst7::SetConst7(TEST_DATA),
           TIC28X::AddbXarnConst7::full_name, TIC28X::AddbXarnConst7::objmode},
          {TIC28X::AddclAccLoc32::SetLoc32(TEST_DATA),
           TIC28X::AddclAccLoc32::full_name, TIC28X::AddclAccLoc32::objmode},
          {TIC28X::AddcuAccLoc16::SetLoc16(TEST_DATA),
           TIC28X::AddcuAccLoc16::full_name, TIC28X::AddcuAccLoc16::objmode},
          {TIC28X::AddlAccLoc32::SetLoc32(TEST_DATA),
           TIC28X::AddlAccLoc32::full_name, TIC28X::AddlAccLoc32::objmode},
          {TIC28X::AddlAccPShiftPm::opcode, TIC28X::AddlAccPShiftPm::full_name,
           TIC28X::AddlAccPShiftPm::objmode},
          {TIC28X::AddlLoc32Acc::SetLoc32(TEST_DATA),
           TIC28X::AddlLoc32Acc::full_name, TIC28X::AddlLoc32Acc::objmode},
          {TIC28X::AdduAccLoc16::SetLoc16(TEST_DATA),
           TIC28X::AdduAccLoc16::full_name, TIC28X::AdduAccLoc16::objmode},
          {TIC28X::AddulPLoc32::SetLoc32(TEST_DATA),
           TIC28X::AddulPLoc32::full_name, TIC28X::AddulPLoc32::objmode},
          {TIC28X::AddulAccLoc32::SetLoc32(TEST_DATA),
           TIC28X::AddulAccLoc32::full_name, TIC28X::AddulAccLoc32::objmode},
          {TIC28X::AdrkImm8::SetImm8(TEST_DATA), TIC28X::AdrkImm8::full_name,
           TIC28X::AdrkImm8::objmode},
          {TIC28X::AndAccConst16Shift0_15::SetConst16(TEST_DATA) |
               TIC28X::AndAccConst16Shift0_15::SetShift(TEST_DATA),
           TIC28X::AndAccConst16Shift0_15::full_name,
           TIC28X::AndAccConst16Shift0_15::objmode},
          {TIC28X::AndAccConst16Shift16::SetConst16(TEST_DATA),
           TIC28X::AndAccConst16Shift16::full_name,
           TIC28X::AndAccConst16Shift16::objmode},
          {TIC28X::AndAccLoc16::SetLoc16(TEST_DATA),
           TIC28X::AndAccLoc16::full_name, TIC28X::AndAccLoc16::objmode},
          {TIC28X::AndAxLoc16Const16::SetLoc16(TEST_DATA) |
               TIC28X::AndAxLoc16Const16::SetConst16(TEST_DATA) |
               TIC28X::AndAxLoc16Const16::SetRegAx(TEST_DATA),
           TIC28X::AndAxLoc16Const16::full_name,
           TIC28X::AndAxLoc16Const16::objmode},
          {TIC28X::AndIerConst16::SetConst16(TEST_DATA),
           TIC28X::AndIerConst16::full_name, TIC28X::AndIerConst16::objmode},
          {TIC28X::AndIfrConst16::SetConst16(TEST_DATA),
           TIC28X::AndIfrConst16::full_name, TIC28X::AndIfrConst16::objmode},
          {TIC28X::AndLoc16Ax::SetLoc16(TEST_DATA) |
               TIC28X::AndLoc16Ax::SetRegAx(TEST_DATA),
           TIC28X::AndLoc16Ax::full_name, TIC28X::AndLoc16Ax::objmode},
          {TIC28X::AndAxLoc16::SetLoc16(TEST_DATA) |
               TIC28X::AndAxLoc16::SetRegAx(TEST_DATA),
           TIC28X::AndAxLoc16::full_name, TIC28X::AndAxLoc16::objmode},
          {TIC28X::AndLoc16Const16::SetLoc16(TEST_DATA) |
               TIC28X::AndLoc16Const16::SetConst16(TEST_DATA),
           TIC28X::AndLoc16Const16::full_name,
           TIC28X::AndLoc16Const16::objmode},
          {TIC28X::AndbAxConst8::SetRegAx(TEST_DATA) |
               TIC28X::AndbAxConst8::SetConst8(TEST_DATA),
           TIC28X::AndbAxConst8::full_name, TIC28X::AndbAxConst8::objmode},
          {TIC28X::Asp::opcode, TIC28X::Asp::full_name, TIC28X::Asp::objmode},
          {TIC28X::AsrAxShift::SetRegAx(TEST_DATA) |
               TIC28X::AsrAxShift::SetShift(TEST_DATA),
           TIC28X::AsrAxShift::full_name, TIC28X::AsrAxShift::objmode},
          {TIC28X::AsrAxT::SetRegAx(TEST_DATA), TIC28X::AsrAxT::full_name,
           TIC28X::AsrAxT::objmode},
          {TIC28X::Asr64AccPShift::SetShift(TEST_DATA),
           TIC28X::Asr64AccPShift::full_name, TIC28X::Asr64AccPShift::objmode},
          {TIC28X::Asr64AccPT::opcode, TIC28X::Asr64AccPT::full_name,
           TIC28X::Asr64AccPT::objmode},
          {TIC28X::AsrlAccT::opcode, TIC28X::AsrlAccT::full_name,
           TIC28X::AsrlAccT::objmode},
          {TIC28X::BOff16Cond::SetOff16(TEST_DATA) |
               TIC28X::BOff16Cond::SetCond(TEST_DATA),
           TIC28X::BOff16Cond::full_name, TIC28X::BOff16Cond::objmode},
          {TIC28X::BanzOff16Arn::SetOff16(TEST_DATA) |
               TIC28X::BanzOff16Arn::SetRegN(TEST_DATA),
           TIC28X::BanzOff16Arn::full_name, TIC28X::BanzOff16Arn::objmode},
          {TIC28X::BarOff16ArnArmEq::SetOff16(TEST_DATA) |
               TIC28X::BarOff16ArnArmEq::SetRegN(TEST_DATA) |
               TIC28X::BarOff16ArnArmEq::SetRegM(TEST_DATA),
           TIC28X::BarOff16ArnArmEq::full_name,
           TIC28X::BarOff16ArnArmEq::objmode},
          {TIC28X::BarOff16ArnArmNeq::SetOff16(TEST_DATA) |
               TIC28X::BarOff16ArnArmNeq::SetRegN(TEST_DATA) |
               TIC28X::BarOff16ArnArmNeq::SetRegM(TEST_DATA),
           TIC28X::BarOff16ArnArmNeq::full_name,
           TIC28X::BarOff16ArnArmNeq::objmode},
          {TIC28X::BfOff16Cond::SetOff16(TEST_DATA) |
               TIC28X::BfOff16Cond::SetCond(TEST_DATA),
           TIC28X::BfOff16Cond::full_name, TIC28X::BfOff16Cond::objmode},
          {TIC28X::ClrcAmode::opcode, TIC28X::ClrcAmode::full_name,
           TIC28X::ClrcAmode::objmode},
          {TIC28X::ClrcM0M1Map::opcode, TIC28X::ClrcM0M1Map::full_name,
           TIC28X::ClrcM0M1Map::objmode},
          {TIC28X::ClrcObjmode::opcode, TIC28X::ClrcObjmode::full_name,
           TIC28X::ClrcObjmode::objmode},
          {TIC28X::ClrcOvc::opcode, TIC28X::ClrcOvc::full_name,
           TIC28X::ClrcOvc::objmode},
          {TIC28X::ClrcXf::opcode, TIC28X::ClrcXf::full_name,
           TIC28X::ClrcXf::objmode},
          {TIC28X::ClrcMode::SetMode(TEST_DATA), TIC28X::ClrcMode::full_name,
           TIC28X::ClrcMode::objmode},
          {TIC28X::CmpAxLoc16::SetRegAx(TEST_DATA) |
               TIC28X::CmpAxLoc16::SetLoc16(TEST_DATA),
           TIC28X::CmpAxLoc16::full_name, TIC28X::CmpAxLoc16::objmode},
          {TIC28X::CmpLoc16Const16::SetConst16(TEST_DATA) |
               TIC28X::CmpLoc16Const16::SetLoc16(TEST_DATA),
           TIC28X::CmpLoc16Const16::full_name,
           TIC28X::CmpLoc16Const16::objmode},
          {TIC28X::Cmp64AccP::opcode, TIC28X::Cmp64AccP::full_name,
           TIC28X::Cmp64AccP::objmode},
          {TIC28X::CmpbAxConst8::SetRegAx(TEST_DATA) |
               TIC28X::CmpbAxConst8::SetConst8(TEST_DATA),
           TIC28X::CmpbAxConst8::full_name, TIC28X::CmpbAxConst8::objmode},
          {TIC28X::CmplAccLoc32::SetLoc32(TEST_DATA),
           TIC28X::CmplAccLoc32::full_name, TIC28X::CmplAccLoc32::objmode},
          {TIC28X::CmplAccPShiftPm::opcode, TIC28X::CmplAccPShiftPm::full_name,
           TIC28X::CmplAccPShiftPm::objmode},
          {TIC28X::Cmpr0::opcode, TIC28X::Cmpr0::full_name,
           TIC28X::Cmpr0::objmode},
          {TIC28X::Cmpr1::opcode, TIC28X::Cmpr1::full_name,
           TIC28X::Cmpr1::objmode},
          {TIC28X::Cmpr2::opcode, TIC28X::Cmpr2::full_name,
           TIC28X::Cmpr2::objmode},
          {TIC28X::Cmpr3::opcode, TIC28X::Cmpr3::full_name,
           TIC28X::Cmpr3::objmode},
          {TIC28X::CsbAcc::opcode, TIC28X::CsbAcc::full_name,
           TIC28X::CsbAcc::objmode},
          {TIC28X::DecLoc16::SetLoc16(TEST_DATA), TIC28X::DecLoc16::full_name,
           TIC28X::DecLoc16::objmode},
          {TIC28X::DmacAccPLoc32Xar7::SetLoc32(TEST_DATA),
           TIC28X::DmacAccPLoc32Xar7::full_name,
           TIC28X::DmacAccPLoc32Xar7::objmode},
          {TIC28X::DmacAccPLoc32Xar7Postinc::SetLoc32(TEST_DATA),
           TIC28X::DmacAccPLoc32Xar7Postinc::full_name,
           TIC28X::DmacAccPLoc32Xar7Postinc::objmode},
          {TIC28X::DmovLoc16::SetLoc16(TEST_DATA), TIC28X::DmovLoc16::full_name,
           TIC28X::DmovLoc16::objmode},
          {TIC28X::Eallow::opcode, TIC28X::Eallow::full_name,
           TIC28X::Eallow::objmode},
          {TIC28X::Edis::opcode, TIC28X::Edis::full_name,
           TIC28X::Edis::objmode},
          {TIC28X::Estop0::opcode, TIC28X::Estop0::full_name,
           TIC28X::Estop0::objmode},
          {TIC28X::Estop1::opcode, TIC28X::Estop1::full_name,
           TIC28X::Estop1::objmode},
          {TIC28X::FfcXar7Const22::SetConst22(TEST_DATA),
           TIC28X::FfcXar7Const22::full_name, TIC28X::FfcXar7Const22::objmode},
          {TIC28X::FlipAx::SetRegAx(TEST_DATA), TIC28X::FlipAx::full_name,
           TIC28X::FlipAx::objmode},
          {TIC28X::IackConst16::SetConst16(TEST_DATA),
           TIC28X::IackConst16::full_name, TIC28X::IackConst16::objmode},
          {TIC28X::Idle::opcode, TIC28X::Idle::full_name,
           TIC28X::Idle::objmode},
          {TIC28X::ImaclPLoc32Xar7::SetLoc32(TEST_DATA),
           TIC28X::ImaclPLoc32Xar7::full_name,
           TIC28X::ImaclPLoc32Xar7::objmode},
          {TIC28X::ImaclPLoc32Xar7Postinc::SetLoc32(TEST_DATA),
           TIC28X::ImaclPLoc32Xar7Postinc::full_name,
           TIC28X::ImaclPLoc32Xar7Postinc::objmode},
          {TIC28X::ImpyalPXtLoc32::SetLoc32(TEST_DATA),
           TIC28X::ImpyalPXtLoc32::full_name, TIC28X::ImpyalPXtLoc32::objmode},
          {TIC28X::ImpylAccXtLoc32::SetLoc32(TEST_DATA),
           TIC28X::ImpylAccXtLoc32::full_name,
           TIC28X::ImpylAccXtLoc32::objmode},
          {TIC28X::ImpylPXtLoc32::SetLoc32(TEST_DATA),
           TIC28X::ImpylPXtLoc32::full_name, TIC28X::ImpylPXtLoc32::objmode},
          {TIC28X::ImpyslPXtLoc32::SetLoc32(TEST_DATA),
           TIC28X::ImpyslPXtLoc32::full_name, TIC28X::ImpyslPXtLoc32::objmode},
          {TIC28X::ImpyxulPXtLoc32::SetLoc32(TEST_DATA),
           TIC28X::ImpyxulPXtLoc32::full_name,
           TIC28X::ImpyxulPXtLoc32::objmode},
          {TIC28X::InLoc16Pa::SetConst16(TEST_DATA) |
               TIC28X::InLoc16Pa::SetLoc16(TEST_DATA),
           TIC28X::InLoc16Pa::full_name, TIC28X::InLoc16Pa::objmode},
          {TIC28X::IncLoc16::SetLoc16(TEST_DATA), TIC28X::IncLoc16::full_name,
           TIC28X::IncLoc16::objmode},
          {TIC28X::IntrIntx::SetIntrX(TEST_DATA), TIC28X::IntrIntx::full_name,
           TIC28X::IntrIntx::objmode},
          {TIC28X::IntrNmi::opcode, TIC28X::IntrNmi::full_name,
           TIC28X::IntrNmi::objmode},
          {TIC28X::IntrEmuint::opcode, TIC28X::IntrEmuint::full_name,
           TIC28X::IntrEmuint::objmode},
          {TIC28X::Iret::opcode, TIC28X::Iret::full_name,
           TIC28X::Iret::objmode},
          {TIC28X::LbXar7::opcode, TIC28X::LbXar7::full_name,
           TIC28X::LbXar7::objmode},
          {TIC28X::LbConst22::SetConst22(TEST_DATA),
           TIC28X::LbConst22::full_name, TIC28X::LbConst22::objmode},
          {TIC28X::LcXar7::opcode, TIC28X::LcXar7::full_name,
           TIC28X::LcXar7::objmode},
          {TIC28X::LcConst22::SetConst22(TEST_DATA),
           TIC28X::LcConst22::full_name, TIC28X::LcConst22::objmode},
          {TIC28X::LcrConst22::SetConst22(TEST_DATA),
           TIC28X::LcrConst22::full_name, TIC28X::LcrConst22::objmode},
          {TIC28X::LcrXarn::SetRegN(TEST_DATA), TIC28X::LcrXarn::full_name,
           TIC28X::LcrXarn::objmode},
          {TIC28X::LoopnzLoc16Const16::SetConst16(TEST_DATA) |
               TIC28X::LoopnzLoc16Const16::SetLoc16(TEST_DATA),
           TIC28X::LoopnzLoc16Const16::full_name,
           TIC28X::LoopnzLoc16Const16::objmode},
          {TIC28X::LoopzLoc16Const16::SetConst16(TEST_DATA) |
               TIC28X::LoopzLoc16Const16::SetLoc16(TEST_DATA),
           TIC28X::LoopzLoc16Const16::full_name,
           TIC28X::LoopzLoc16Const16::objmode},
          {TIC28X::Lpaddr::opcode, TIC28X::Lpaddr::full_name,
           TIC28X::Lpaddr::objmode},
          {TIC28X::Lret::opcode, TIC28X::Lret::full_name,
           TIC28X::Lret::objmode},
          {TIC28X::Lrete::opcode, TIC28X::Lrete::full_name,
           TIC28X::Lrete::objmode},
          {TIC28X::Lretr::opcode, TIC28X::Lretr::full_name,
           TIC28X::Lretr::objmode},
          {TIC28X::LslAccShift::SetShift(TEST_DATA),
           TIC28X::LslAccShift::full_name, TIC28X::LslAccShift::objmode},
          {TIC28X::LslAccT::opcode, TIC28X::LslAccT::full_name,
           TIC28X::LslAccT::objmode},
          {TIC28X::LslAxShift::SetRegAx(TEST_DATA) |
               TIC28X::LslAxShift::SetShift(TEST_DATA),
           TIC28X::LslAxShift::full_name, TIC28X::LslAxShift::objmode},
          {TIC28X::LslAxT::SetRegAx(TEST_DATA), TIC28X::LslAxT::full_name,
           TIC28X::LslAxT::objmode},
          {TIC28X::Lsl64AccPShift::SetShift(TEST_DATA),
           TIC28X::Lsl64AccPShift::full_name, TIC28X::Lsl64AccPShift::objmode},
          {TIC28X::Lsl64AccPT::opcode, TIC28X::Lsl64AccPT::full_name,
           TIC28X::Lsl64AccPT::objmode},
          {TIC28X::LsllAccT::opcode, TIC28X::LsllAccT::full_name,
           TIC28X::LsllAccT::objmode},
          {TIC28X::LsrAxShift::SetRegAx(TEST_DATA) |
               TIC28X::LsrAxShift::SetShift(TEST_DATA),
           TIC28X::LsrAxShift::full_name, TIC28X::LsrAxShift::objmode},
          {TIC28X::LsrAxT::SetRegAx(TEST_DATA), TIC28X::LsrAxT::full_name,
           TIC28X::LsrAxT::objmode},
          {TIC28X::Lsr64AccPShift::SetShift(TEST_DATA),
           TIC28X::Lsr64AccPShift::full_name, TIC28X::Lsr64AccPShift::objmode},
          {TIC28X::Lsr64AccPT::opcode, TIC28X::Lsr64AccPT::full_name,
           TIC28X::Lsr64AccPT::objmode},
          {TIC28X::LsrlAccT::opcode, TIC28X::LsrlAccT::full_name,
           TIC28X::LsrlAccT::objmode},
          {TIC28X::MacPLoc16Pma::SetLoc16(TEST_DATA) |
               TIC28X::MacPLoc16Pma::SetConst16(TEST_DATA),
           TIC28X::MacPLoc16Pma::full_name, TIC28X::MacPLoc16Pma::objmode},
          {TIC28X::MacPLoc16Xar7::SetLoc16(TEST_DATA),
           TIC28X::MacPLoc16Xar7::full_name, TIC28X::MacPLoc16Xar7::objmode},
          {TIC28X::MacPLoc16Xar7Postinc::SetLoc16(TEST_DATA),
           TIC28X::MacPLoc16Xar7Postinc::full_name,
           TIC28X::MacPLoc16Xar7Postinc::objmode},
          {TIC28X::MaxAxLoc16::SetLoc16(TEST_DATA) |
               TIC28X::MaxAxLoc16::SetRegAx(TEST_DATA),
           TIC28X::MaxAxLoc16::full_name, TIC28X::MaxAxLoc16::objmode},
          {TIC28X::MaxculPLoc32::SetLoc32(TEST_DATA),
           TIC28X::MaxculPLoc32::full_name, TIC28X::MaxculPLoc32::objmode},
          {TIC28X::MaxlAccLoc32::SetLoc32(TEST_DATA),
           TIC28X::MaxlAccLoc32::full_name, TIC28X::MaxlAccLoc32::objmode},
          {TIC28X::MinAxLoc16::SetLoc16(TEST_DATA) |
               TIC28X::MinAxLoc16::SetRegAx(TEST_DATA),
           TIC28X::MinAxLoc16::full_name, TIC28X::MinAxLoc16::objmode},
          {TIC28X::MinculPLoc32::SetLoc32(TEST_DATA),
           TIC28X::MinculPLoc32::full_name, TIC28X::MinculPLoc32::objmode},
          {TIC28X::MinlAccLoc32::SetLoc32(TEST_DATA),
           TIC28X::MinlAccLoc32::full_name, TIC28X::MinlAccLoc32::objmode},
          {TIC28X::MovMem16Loc16::SetLoc16(TEST_DATA) |
               TIC28X::MovMem16Loc16::SetConst16(TEST_DATA),
           TIC28X::MovMem16Loc16::full_name, TIC28X::MovMem16Loc16::objmode},
          {TIC28X::MovAccConst16Shift::SetShift(TEST_DATA) |
               TIC28X::MovAccConst16Shift::SetConst16(TEST_DATA),
           TIC28X::MovAccConst16Shift::full_name,
           TIC28X::MovAccConst16Shift::objmode},
          {TIC28X::MovAccLoc16ShiftT::SetLoc16(TEST_DATA),
           TIC28X::MovAccLoc16ShiftT::full_name,
           TIC28X::MovAccLoc16ShiftT::objmode},
          {TIC28X::MovAccLoc16Objmode1::SetLoc16(TEST_DATA),
           TIC28X::MovAccLoc16Objmode1::full_name,
           TIC28X::MovAccLoc16Objmode1::objmode},
          {TIC28X::MovAccLoc16Objmode0::SetLoc16(TEST_DATA),
           TIC28X::MovAccLoc16Objmode0::full_name,
           TIC28X::MovAccLoc16Objmode0::objmode},
          {TIC28X::MovAccLoc16Shift1_15Objmode1::SetShift(TEST_DATA) |
               TIC28X::MovAccLoc16Shift1_15Objmode1::SetLoc16(TEST_DATA),
           TIC28X::MovAccLoc16Shift1_15Objmode1::full_name,
           TIC28X::MovAccLoc16Shift1_15Objmode1::objmode},
          {TIC28X::MovAccLoc16Shift1_15Objmode0::SetShift(TEST_DATA) |
               TIC28X::MovAccLoc16Shift1_15Objmode0::SetLoc16(TEST_DATA),
           TIC28X::MovAccLoc16Shift1_15Objmode0::full_name,
           TIC28X::MovAccLoc16Shift1_15Objmode0::objmode},
          {TIC28X::MovAccLoc16Shift16::SetLoc16(TEST_DATA),
           TIC28X::MovAccLoc16Shift16::full_name,
           TIC28X::MovAccLoc16Shift16::objmode},
          {TIC28X::MovAr6Loc16::SetLoc16(TEST_DATA),
           TIC28X::MovAr6Loc16::full_name, TIC28X::MovAr6Loc16::objmode},
          {TIC28X::MovAr7Loc16::SetLoc16(TEST_DATA),
           TIC28X::MovAr7Loc16::full_name, TIC28X::MovAr7Loc16::objmode},
          {TIC28X::MovAxLoc16::SetRegAx(TEST_DATA) |
               TIC28X::MovAxLoc16::SetLoc16(TEST_DATA),
           TIC28X::MovAxLoc16::full_name, TIC28X::MovAxLoc16::objmode},
          {TIC28X::MovDpConst10::SetConst10(TEST_DATA),
           TIC28X::MovDpConst10::full_name, TIC28X::MovDpConst10::objmode},
          {TIC28X::MovIerLoc16::SetLoc16(TEST_DATA),
           TIC28X::MovIerLoc16::full_name, TIC28X::MovIerLoc16::objmode},
          {TIC28X::MovLoc16Const16::SetConst16(TEST_DATA) |
               TIC28X::MovLoc16Const16::SetLoc16(TEST_DATA),
           TIC28X::MovLoc16Const16::full_name,
           TIC28X::MovLoc16Const16::objmode},
          {TIC28X::MovLoc16Mem16::SetConst16(TEST_DATA) |
               TIC28X::MovLoc16Mem16::SetLoc16(TEST_DATA),
           TIC28X::MovLoc16Mem16::full_name, TIC28X::MovLoc16Mem16::objmode},
          {TIC28X::MovLoc16_0::SetLoc16(TEST_DATA),
           TIC28X::MovLoc16_0::full_name, TIC28X::MovLoc16_0::objmode},
          {TIC28X::MovLoc16AccShift1::SetLoc16(TEST_DATA),
           TIC28X::MovLoc16AccShift1::full_name,
           TIC28X::MovLoc16AccShift1::objmode},
          {TIC28X::MovLoc16AccShift2_8Objmode1::SetShift(TEST_DATA) |
               TIC28X::MovLoc16AccShift2_8Objmode1::SetLoc16(TEST_DATA),
           TIC28X::MovLoc16AccShift2_8Objmode1::full_name,
           TIC28X::MovLoc16AccShift2_8Objmode1::objmode},
          {TIC28X::MovLoc16AccShift2_8Objmode0::SetShift(TEST_DATA) |
               TIC28X::MovLoc16AccShift2_8Objmode0::SetLoc16(TEST_DATA),
           TIC28X::MovLoc16AccShift2_8Objmode0::full_name,
           TIC28X::MovLoc16AccShift2_8Objmode0::objmode},
          {TIC28X::MovLoc16Arn::SetRegN(TEST_DATA) |
               TIC28X::MovLoc16Arn::SetLoc16(TEST_DATA),
           TIC28X::MovLoc16Arn::full_name, TIC28X::MovLoc16Arn::objmode},
          {TIC28X::MovLoc16Ax::SetRegAx(TEST_DATA) |
               TIC28X::MovLoc16Ax::SetLoc16(TEST_DATA),
           TIC28X::MovLoc16Ax::full_name, TIC28X::MovLoc16Ax::objmode},
          {TIC28X::MovLoc16AxCond::SetRegAx(TEST_DATA) |
               TIC28X::MovLoc16AxCond::SetLoc16(TEST_DATA) |
               TIC28X::MovLoc16AxCond::SetCond(TEST_DATA),
           TIC28X::MovLoc16AxCond::full_name, TIC28X::MovLoc16AxCond::objmode},
          {TIC28X::MovLoc16Ier::SetLoc16(TEST_DATA),
           TIC28X::MovLoc16Ier::full_name, TIC28X::MovLoc16Ier::objmode},
          {TIC28X::MovLoc16Ovc::SetLoc16(TEST_DATA),
           TIC28X::MovLoc16Ovc::full_name, TIC28X::MovLoc16Ovc::objmode},
          {TIC28X::MovLoc16P::SetLoc16(TEST_DATA), TIC28X::MovLoc16P::full_name,
           TIC28X::MovLoc16P::objmode},
          {TIC28X::MovLoc16T::SetLoc16(TEST_DATA), TIC28X::MovLoc16T::full_name,
           TIC28X::MovLoc16T::objmode},
          {TIC28X::MovOvcLoc16::SetLoc16(TEST_DATA),
           TIC28X::MovOvcLoc16::full_name, TIC28X::MovOvcLoc16::objmode},
          {TIC28X::MovPhLoc16::SetLoc16(TEST_DATA),
           TIC28X::MovPhLoc16::full_name, TIC28X::MovPhLoc16::objmode},
          {TIC28X::MovPlLoc16::SetLoc16(TEST_DATA),
           TIC28X::MovPlLoc16::full_name, TIC28X::MovPlLoc16::objmode},
          {TIC28X::MovPmAx::SetRegAx(TEST_DATA), TIC28X::MovPmAx::full_name,
           TIC28X::MovPmAx::objmode},
          {TIC28X::MovTLoc16::SetLoc16(TEST_DATA), TIC28X::MovTLoc16::full_name,
           TIC28X::MovTLoc16::objmode},
          {TIC28X::MovTl0::opcode, TIC28X::MovTl0::full_name,
           TIC28X::MovTl0::objmode},
          {TIC28X::MovXarnPc::SetRegN(TEST_DATA), TIC28X::MovXarnPc::full_name,
           TIC28X::MovXarnPc::objmode},
          {TIC28X::MovaTLoc16::SetLoc16(TEST_DATA),
           TIC28X::MovaTLoc16::full_name, TIC28X::MovaTLoc16::objmode},
          {TIC28X::MovadTLoc16::SetLoc16(TEST_DATA),
           TIC28X::MovadTLoc16::full_name, TIC28X::MovadTLoc16::objmode},
          {TIC28X::MovbAccConst8::SetConst8(TEST_DATA),
           TIC28X::MovbAccConst8::full_name, TIC28X::MovbAccConst8::objmode},
          {TIC28X::MovbAr6Const8::SetConst8(TEST_DATA),
           TIC28X::MovbAr6Const8::full_name, TIC28X::MovbAr6Const8::objmode},
          {TIC28X::MovbAr7Const8::SetConst8(TEST_DATA),
           TIC28X::MovbAr7Const8::full_name, TIC28X::MovbAr7Const8::objmode},
          {TIC28X::MovbAxConst8::SetRegAx(TEST_DATA) |
               TIC28X::MovbAxConst8::SetConst8(TEST_DATA),
           TIC28X::MovbAxConst8::full_name, TIC28X::MovbAxConst8::objmode},
          {TIC28X::MovbAxlsbLoc16::SetRegAx(TEST_DATA) |
               TIC28X::MovbAxlsbLoc16::SetLoc16(TEST_DATA),
           TIC28X::MovbAxlsbLoc16::full_name, TIC28X::MovbAxlsbLoc16::objmode},
          {TIC28X::MovbAxmsbLoc16::SetRegAx(TEST_DATA) |
               TIC28X::MovbAxmsbLoc16::SetLoc16(TEST_DATA),
           TIC28X::MovbAxmsbLoc16::full_name, TIC28X::MovbAxmsbLoc16::objmode},
          {TIC28X::MovbLoc16Const8Cond::SetLoc16(TEST_DATA) |
               TIC28X::MovbLoc16Const8Cond::SetConst8(TEST_DATA) |
               TIC28X::MovbLoc16Const8Cond::SetCond(TEST_DATA),
           TIC28X::MovbLoc16Const8Cond::full_name,
           TIC28X::MovbLoc16Const8Cond::objmode},
          {TIC28X::MovbLoc16Axlsb::SetRegAx(TEST_DATA) |
               TIC28X::MovbLoc16Axlsb::SetLoc16(TEST_DATA),
           TIC28X::MovbLoc16Axlsb::full_name, TIC28X::MovbLoc16Axlsb::objmode},
          {TIC28X::MovbLoc16Axmsb::SetRegAx(TEST_DATA) |
               TIC28X::MovbLoc16Axmsb::SetLoc16(TEST_DATA),
           TIC28X::MovbLoc16Axmsb::full_name, TIC28X::MovbLoc16Axmsb::objmode},
          {TIC28X::MovbXar0Const8::SetConst8(TEST_DATA),
           TIC28X::MovbXar0Const8::full_name, TIC28X::MovbXar0Const8::objmode},
          {TIC28X::MovbXar1Const8::SetConst8(TEST_DATA),
           TIC28X::MovbXar1Const8::full_name, TIC28X::MovbXar1Const8::objmode},
          {TIC28X::MovbXar2Const8::SetConst8(TEST_DATA),
           TIC28X::MovbXar2Const8::full_name, TIC28X::MovbXar2Const8::objmode},
          {TIC28X::MovbXar3Const8::SetConst8(TEST_DATA),
           TIC28X::MovbXar3Const8::full_name, TIC28X::MovbXar3Const8::objmode},
          {TIC28X::MovbXar4Const8::SetConst8(TEST_DATA),
           TIC28X::MovbXar4Const8::full_name, TIC28X::MovbXar4Const8::objmode},
          {TIC28X::MovbXar5Const8::SetConst8(TEST_DATA),
           TIC28X::MovbXar5Const8::full_name, TIC28X::MovbXar5Const8::objmode},
          {TIC28X::MovbXar6Const8::SetConst8(TEST_DATA),
           TIC28X::MovbXar6Const8::full_name, TIC28X::MovbXar6Const8::objmode},
          {TIC28X::MovbXar7Const8::SetConst8(TEST_DATA),
           TIC28X::MovbXar7Const8::full_name, TIC28X::MovbXar7Const8::objmode},
          {TIC28X::MovdlXtLoc32::SetLoc32(TEST_DATA),
           TIC28X::MovdlXtLoc32::full_name, TIC28X::MovdlXtLoc32::objmode},
          {TIC28X::MovhLoc16AccShift1::SetLoc16(TEST_DATA),
           TIC28X::MovhLoc16AccShift1::full_name,
           TIC28X::MovhLoc16AccShift1::objmode},
          {TIC28X::MovhLoc16AccShift2_8Objmode1::SetLoc16(TEST_DATA) |
               TIC28X::MovhLoc16AccShift2_8Objmode1::SetShift(TEST_DATA),
           TIC28X::MovhLoc16AccShift2_8Objmode1::full_name,
           TIC28X::MovhLoc16AccShift2_8Objmode1::objmode},
          {TIC28X::MovhLoc16AccShift2_8Objmode0::SetLoc16(TEST_DATA) |
               TIC28X::MovhLoc16AccShift2_8Objmode0::SetShift(TEST_DATA),
           TIC28X::MovhLoc16AccShift2_8Objmode0::full_name,
           TIC28X::MovhLoc16AccShift2_8Objmode0::objmode},
          {TIC28X::MovhLoc16P::SetLoc16(TEST_DATA),
           TIC28X::MovhLoc16P::full_name, TIC28X::MovhLoc16P::objmode},
          {TIC28X::MovlAccLoc32::SetLoc32(TEST_DATA),
           TIC28X::MovlAccLoc32::full_name, TIC28X::MovlAccLoc32::objmode},
          {TIC28X::MovlAccPShiftPm::opcode, TIC28X::MovlAccPShiftPm::full_name,
           TIC28X::MovlAccPShiftPm::objmode},
          {TIC28X::MovlLoc32Acc::SetLoc32(TEST_DATA),
           TIC28X::MovlLoc32Acc::full_name, TIC28X::MovlLoc32Acc::objmode},
          {TIC28X::MovlLoc32AccCond::SetLoc32(TEST_DATA) |
               TIC28X::MovlLoc32AccCond::SetCond(TEST_DATA),
           TIC28X::MovlLoc32AccCond::full_name,
           TIC28X::MovlLoc32AccCond::objmode},
          {TIC28X::MovlLoc32P::SetLoc32(TEST_DATA),
           TIC28X::MovlLoc32P::full_name, TIC28X::MovlLoc32P::objmode},
          {TIC28X::MovlLoc32Xar0::SetLoc32(TEST_DATA),
           TIC28X::MovlLoc32Xar0::full_name, TIC28X::MovlLoc32Xar0::objmode},
          {TIC28X::MovlLoc32Xar1::SetLoc32(TEST_DATA),
           TIC28X::MovlLoc32Xar1::full_name, TIC28X::MovlLoc32Xar1::objmode},
          {TIC28X::MovlLoc32Xar2::SetLoc32(TEST_DATA),
           TIC28X::MovlLoc32Xar2::full_name, TIC28X::MovlLoc32Xar2::objmode},
          {TIC28X::MovlLoc32Xar3::SetLoc32(TEST_DATA),
           TIC28X::MovlLoc32Xar3::full_name, TIC28X::MovlLoc32Xar3::objmode},
          {TIC28X::MovlLoc32Xar4::SetLoc32(TEST_DATA),
           TIC28X::MovlLoc32Xar4::full_name, TIC28X::MovlLoc32Xar4::objmode},
          {TIC28X::MovlLoc32Xar5::SetLoc32(TEST_DATA),
           TIC28X::MovlLoc32Xar5::full_name, TIC28X::MovlLoc32Xar5::objmode},
          {TIC28X::MovlLoc32Xar6::SetLoc32(TEST_DATA),
           TIC28X::MovlLoc32Xar6::full_name, TIC28X::MovlLoc32Xar6::objmode},
          {TIC28X::MovlLoc32Xar7::SetLoc32(TEST_DATA),
           TIC28X::MovlLoc32Xar7::full_name, TIC28X::MovlLoc32Xar7::objmode},
          {TIC28X::MovlLoc32Xt::SetLoc32(TEST_DATA),
           TIC28X::MovlLoc32Xt::full_name, TIC28X::MovlLoc32Xt::objmode},
          {TIC28X::MovlPAcc::opcode, TIC28X::MovlPAcc::full_name,
           TIC28X::MovlPAcc::objmode},
          {TIC28X::MovlPLoc32::SetLoc32(TEST_DATA),
           TIC28X::MovlPLoc32::full_name, TIC28X::MovlPLoc32::objmode},
          {TIC28X::MovlXar0Loc32::SetLoc32(TEST_DATA),
           TIC28X::MovlXar0Loc32::full_name, TIC28X::MovlXar0Loc32::objmode},
          {TIC28X::MovlXar1Loc32::SetLoc32(TEST_DATA),
           TIC28X::MovlXar1Loc32::full_name, TIC28X::MovlXar1Loc32::objmode},
          {TIC28X::MovlXar2Loc32::SetLoc32(TEST_DATA),
           TIC28X::MovlXar2Loc32::full_name, TIC28X::MovlXar2Loc32::objmode},
          {TIC28X::MovlXar3Loc32::SetLoc32(TEST_DATA),
           TIC28X::MovlXar3Loc32::full_name, TIC28X::MovlXar3Loc32::objmode},
          {TIC28X::MovlXar4Loc32::SetLoc32(TEST_DATA),
           TIC28X::MovlXar4Loc32::full_name, TIC28X::MovlXar4Loc32::objmode},
          {TIC28X::MovlXar5Loc32::SetLoc32(TEST_DATA),
           TIC28X::MovlXar5Loc32::full_name, TIC28X::MovlXar5Loc32::objmode},
          {TIC28X::MovlXar6Loc32::SetLoc32(TEST_DATA),
           TIC28X::MovlXar6Loc32::full_name, TIC28X::MovlXar6Loc32::objmode},
          {TIC28X::MovlXar7Loc32::SetLoc32(TEST_DATA),
           TIC28X::MovlXar7Loc32::full_name, TIC28X::MovlXar7Loc32::objmode},
          {TIC28X::MovlXar0Const22::SetConst22(TEST_DATA),
           TIC28X::MovlXar0Const22::full_name,
           TIC28X::MovlXar0Const22::objmode},
          {TIC28X::MovlXar1Const22::SetConst22(TEST_DATA),
           TIC28X::MovlXar1Const22::full_name,
           TIC28X::MovlXar1Const22::objmode},
          {TIC28X::MovlXar2Const22::SetConst22(TEST_DATA),
           TIC28X::MovlXar2Const22::full_name,
           TIC28X::MovlXar2Const22::objmode},
          {TIC28X::MovlXar3Const22::SetConst22(TEST_DATA),
           TIC28X::MovlXar3Const22::full_name,
           TIC28X::MovlXar3Const22::objmode},
          {TIC28X::MovlXar4Const22::SetConst22(TEST_DATA),
           TIC28X::MovlXar4Const22::full_name,
           TIC28X::MovlXar4Const22::objmode},
          {TIC28X::MovlXar5Const22::SetConst22(TEST_DATA),
           TIC28X::MovlXar5Const22::full_name,
           TIC28X::MovlXar5Const22::objmode},
          {TIC28X::MovlXar6Const22::SetConst22(TEST_DATA),
           TIC28X::MovlXar6Const22::full_name,
           TIC28X::MovlXar6Const22::objmode},
          {TIC28X::MovlXar7Const22::SetConst22(TEST_DATA),
           TIC28X::MovlXar7Const22::full_name,
           TIC28X::MovlXar7Const22::objmode},
          {TIC28X::MovlXtLoc32::SetLoc32(TEST_DATA),
           TIC28X::MovlXtLoc32::full_name, TIC28X::MovlXtLoc32::objmode},
          {TIC28X::MovpTLoc16::SetLoc16(TEST_DATA),
           TIC28X::MovpTLoc16::full_name, TIC28X::MovpTLoc16::objmode},
          {TIC28X::MovsTLoc16::SetLoc16(TEST_DATA),
           TIC28X::MovsTLoc16::full_name, TIC28X::MovsTLoc16::objmode},
          {TIC28X::MovuAccLoc16::SetLoc16(TEST_DATA),
           TIC28X::MovuAccLoc16::full_name, TIC28X::MovuAccLoc16::objmode},
          {TIC28X::MovuLoc16Ovc::SetLoc16(TEST_DATA),
           TIC28X::MovuLoc16Ovc::full_name, TIC28X::MovuLoc16Ovc::objmode},
          {TIC28X::MovuOvcLoc16::SetLoc16(TEST_DATA),
           TIC28X::MovuOvcLoc16::full_name, TIC28X::MovuOvcLoc16::objmode},
          {TIC28X::MovwDpConst16::SetConst16(TEST_DATA),
           TIC28X::MovwDpConst16::full_name, TIC28X::MovwDpConst16::objmode},
          {TIC28X::MovxTlLoc16::SetLoc16(TEST_DATA),
           TIC28X::MovxTlLoc16::full_name, TIC28X::MovxTlLoc16::objmode},
          {TIC28X::MovzAr0Loc16::SetLoc16(TEST_DATA),
           TIC28X::MovzAr0Loc16::full_name, TIC28X::MovzAr0Loc16::objmode},
          {TIC28X::MovzAr1Loc16::SetLoc16(TEST_DATA),
           TIC28X::MovzAr1Loc16::full_name, TIC28X::MovzAr1Loc16::objmode},
          {TIC28X::MovzAr2Loc16::SetLoc16(TEST_DATA),
           TIC28X::MovzAr2Loc16::full_name, TIC28X::MovzAr2Loc16::objmode},
          {TIC28X::MovzAr3Loc16::SetLoc16(TEST_DATA),
           TIC28X::MovzAr3Loc16::full_name, TIC28X::MovzAr3Loc16::objmode},
          {TIC28X::MovzAr4Loc16::SetLoc16(TEST_DATA),
           TIC28X::MovzAr4Loc16::full_name, TIC28X::MovzAr4Loc16::objmode},
          {TIC28X::MovzAr5Loc16::SetLoc16(TEST_DATA),
           TIC28X::MovzAr5Loc16::full_name, TIC28X::MovzAr5Loc16::objmode},
          {TIC28X::MovzAr6Loc16::SetLoc16(TEST_DATA),
           TIC28X::MovzAr6Loc16::full_name, TIC28X::MovzAr6Loc16::objmode},
          {TIC28X::MovzAr7Loc16::SetLoc16(TEST_DATA),
           TIC28X::MovzAr7Loc16::full_name, TIC28X::MovzAr7Loc16::objmode},
          {TIC28X::MovzDpConst10::SetConst10(TEST_DATA),
           TIC28X::MovzDpConst10::full_name, TIC28X::MovzDpConst10::objmode},
          {TIC28X::MpyAccLoc16Const16::SetLoc16(TEST_DATA) |
               TIC28X::MpyAccLoc16Const16::SetConst16(TEST_DATA),
           TIC28X::MpyAccLoc16Const16::full_name,
           TIC28X::MpyAccLoc16Const16::objmode},
          {TIC28X::MpyAccTLoc16::SetLoc16(TEST_DATA),
           TIC28X::MpyAccTLoc16::full_name, TIC28X::MpyAccTLoc16::objmode},
          {TIC28X::MpyPLoc16Const16::SetLoc16(TEST_DATA) |
               TIC28X::MpyPLoc16Const16::SetConst16(TEST_DATA),
           TIC28X::MpyPLoc16Const16::full_name,
           TIC28X::MpyPLoc16Const16::objmode},
          {TIC28X::MpyPTLoc16::SetLoc16(TEST_DATA),
           TIC28X::MpyPTLoc16::full_name, TIC28X::MpyPTLoc16::objmode},
          {TIC28X::MpyaPLoc16Const16::SetLoc16(TEST_DATA) |
               TIC28X::MpyaPLoc16Const16::SetConst16(TEST_DATA),
           TIC28X::MpyaPLoc16Const16::full_name,
           TIC28X::MpyaPLoc16Const16::objmode},
          {TIC28X::MpyaPTLoc16::SetLoc16(TEST_DATA),
           TIC28X::MpyaPTLoc16::full_name, TIC28X::MpyaPTLoc16::objmode},
          {TIC28X::MpybAccTConst8::SetConst8(TEST_DATA),
           TIC28X::MpybAccTConst8::full_name, TIC28X::MpybAccTConst8::objmode},
          {TIC28X::MpybPTConst8::SetConst8(TEST_DATA),
           TIC28X::MpybPTConst8::full_name, TIC28X::MpybPTConst8::objmode},
          {TIC28X::MpysPTLoc16::SetLoc16(TEST_DATA),
           TIC28X::MpysPTLoc16::full_name, TIC28X::MpysPTLoc16::objmode},
          {TIC28X::MpyuPTLoc16::SetLoc16(TEST_DATA),
           TIC28X::MpyuPTLoc16::full_name, TIC28X::MpyuPTLoc16::objmode},
          {TIC28X::MpyuAccTLoc16::SetLoc16(TEST_DATA),
           TIC28X::MpyuAccTLoc16::full_name, TIC28X::MpyuAccTLoc16::objmode},
          {TIC28X::MpyxuAccTLoc16::SetLoc16(TEST_DATA),
           TIC28X::MpyxuAccTLoc16::full_name, TIC28X::MpyxuAccTLoc16::objmode},
          {TIC28X::MpyxuPTLoc16::SetLoc16(TEST_DATA),
           TIC28X::MpyxuPTLoc16::full_name, TIC28X::MpyxuPTLoc16::objmode},
          {TIC28X::Nasp::opcode, TIC28X::Nasp::full_name,
           TIC28X::Nasp::objmode},
          {TIC28X::NegAcc::opcode, TIC28X::NegAcc::full_name,
           TIC28X::NegAcc::objmode},
          {TIC28X::NegAx::SetRegAx(TEST_DATA), TIC28X::NegAx::full_name,
           TIC28X::NegAx::objmode},
          {TIC28X::Neg64AccP::opcode, TIC28X::Neg64AccP::full_name,
           TIC28X::Neg64AccP::objmode},
          {TIC28X::NegtcAcc::opcode, TIC28X::NegtcAcc::full_name,
           TIC28X::NegtcAcc::objmode},
          {TIC28X::NopIndArpn::SetInd(TEST_DATA), TIC28X::NopIndArpn::full_name,
           TIC28X::NopIndArpn::objmode},
          {TIC28X::NormAccInd::opcode, TIC28X::NormAccInd::full_name,
           TIC28X::NormAccInd::objmode},
          {TIC28X::NormAccIndPostinc::opcode,
           TIC28X::NormAccIndPostinc::full_name,
           TIC28X::NormAccIndPostinc::objmode},
          {TIC28X::NormAccIndPostdec::opcode,
           TIC28X::NormAccIndPostdec::full_name,
           TIC28X::NormAccIndPostdec::objmode},
          {TIC28X::NormAccInd0Postinc::opcode,
           TIC28X::NormAccInd0Postinc::full_name,
           TIC28X::NormAccInd0Postinc::objmode},
          {TIC28X::NormAccInd0Postdec::opcode,
           TIC28X::NormAccInd0Postdec::full_name,
           TIC28X::NormAccInd0Postdec::objmode},
          {TIC28X::NormAccXarnPostinc::SetRegN(TEST_DATA),
           TIC28X::NormAccXarnPostinc::full_name,
           TIC28X::NormAccXarnPostinc::objmode},
          {TIC28X::NormAccXarnPostdec::SetRegN(TEST_DATA),
           TIC28X::NormAccXarnPostdec::full_name,
           TIC28X::NormAccXarnPostdec::objmode},
          {TIC28X::NotAcc::opcode, TIC28X::NotAcc::full_name,
           TIC28X::NotAcc::objmode},
          {TIC28X::NotAx::SetRegAx(TEST_DATA), TIC28X::NotAx::full_name,
           TIC28X::NotAx::objmode},
          {TIC28X::OrAccLoc16::SetLoc16(TEST_DATA),
           TIC28X::OrAccLoc16::full_name, TIC28X::OrAccLoc16::objmode},
          {TIC28X::OrAccConst16Shift0_15::SetShift(TEST_DATA) |
               TIC28X::OrAccConst16Shift0_15::SetConst16(TEST_DATA),
           TIC28X::OrAccConst16Shift0_15::full_name,
           TIC28X::OrAccConst16Shift0_15::objmode},
          {TIC28X::OrAccConst16Shift16::SetConst16(TEST_DATA),
           TIC28X::OrAccConst16Shift16::full_name,
           TIC28X::OrAccConst16Shift16::objmode},
          {TIC28X::OrAxLoc16::SetLoc16(TEST_DATA) |
               TIC28X::OrAxLoc16::SetRegAx(TEST_DATA),
           TIC28X::OrAxLoc16::full_name, TIC28X::OrAxLoc16::objmode},
          {TIC28X::OrIerConst16::SetConst16(TEST_DATA),
           TIC28X::OrIerConst16::full_name, TIC28X::OrIerConst16::objmode},
          {TIC28X::OrIfrConst16::SetConst16(TEST_DATA),
           TIC28X::OrIfrConst16::full_name, TIC28X::OrIfrConst16::objmode},
          {TIC28X::OrLoc16Const16::SetLoc16(TEST_DATA) |
               TIC28X::OrLoc16Const16::SetConst16(TEST_DATA),
           TIC28X::OrLoc16Const16::full_name, TIC28X::OrLoc16Const16::objmode},
          {TIC28X::OrLoc16Ax::SetLoc16(TEST_DATA) |
               TIC28X::OrLoc16Ax::SetRegAx(TEST_DATA),
           TIC28X::OrLoc16Ax::full_name, TIC28X::OrLoc16Ax::objmode},
          {TIC28X::OrbAxConst8::SetConst8(TEST_DATA) |
               TIC28X::OrbAxConst8::SetRegAx(TEST_DATA),
           TIC28X::OrbAxConst8::full_name, TIC28X::OrbAxConst8::objmode},
          {TIC28X::OutPaLoc16::SetLoc16(TEST_DATA) |
               TIC28X::OutPaLoc16::SetConst16(TEST_DATA),
           TIC28X::OutPaLoc16::full_name, TIC28X::OutPaLoc16::objmode},
          {TIC28X::PopAr1Ar0::opcode, TIC28X::PopAr1Ar0::full_name,
           TIC28X::PopAr1Ar0::objmode},
          {TIC28X::PopAr3Ar2::opcode, TIC28X::PopAr3Ar2::full_name,
           TIC28X::PopAr3Ar2::objmode},
          {TIC28X::PopAr5Ar4::opcode, TIC28X::PopAr5Ar4::full_name,
           TIC28X::PopAr5Ar4::objmode},
          {TIC28X::PopAr1hAr0h::opcode, TIC28X::PopAr1hAr0h::full_name,
           TIC28X::PopAr1hAr0h::objmode},
          {TIC28X::PopDbgier::opcode, TIC28X::PopDbgier::full_name,
           TIC28X::PopDbgier::objmode},
          {TIC28X::PopDp::opcode, TIC28X::PopDp::full_name,
           TIC28X::PopDp::objmode},
          {TIC28X::PopDpSt1::opcode, TIC28X::PopDpSt1::full_name,
           TIC28X::PopDpSt1::objmode},
          {TIC28X::PopIfr::opcode, TIC28X::PopIfr::full_name,
           TIC28X::PopIfr::objmode},
          {TIC28X::PopLoc16::SetLoc16(TEST_DATA), TIC28X::PopLoc16::full_name,
           TIC28X::PopLoc16::objmode},
          {TIC28X::PopP::opcode, TIC28X::PopP::full_name,
           TIC28X::PopP::objmode},
          {TIC28X::PopRpc::opcode, TIC28X::PopRpc::full_name,
           TIC28X::PopRpc::objmode},
          {TIC28X::PopSt0::opcode, TIC28X::PopSt0::full_name,
           TIC28X::PopSt0::objmode},
          {TIC28X::PopSt1::opcode, TIC28X::PopSt1::full_name,
           TIC28X::PopSt1::objmode},
          {TIC28X::PopTSt0::opcode, TIC28X::PopTSt0::full_name,
           TIC28X::PopTSt0::objmode},
          {TIC28X::PopXt::opcode, TIC28X::PopXt::full_name,
           TIC28X::PopXt::objmode},
          {TIC28X::PreadLoc16Xar7::SetLoc16(TEST_DATA),
           TIC28X::PreadLoc16Xar7::full_name, TIC28X::PreadLoc16Xar7::objmode},
          {TIC28X::PushAr1Ar0::opcode, TIC28X::PushAr1Ar0::full_name,
           TIC28X::PushAr1Ar0::objmode},
          {TIC28X::PushAr3Ar2::opcode, TIC28X::PushAr3Ar2::full_name,
           TIC28X::PushAr3Ar2::objmode},
          {TIC28X::PushAr5Ar4::opcode, TIC28X::PushAr5Ar4::full_name,
           TIC28X::PushAr5Ar4::objmode},
          {TIC28X::PushAr1hAr0h::opcode, TIC28X::PushAr1hAr0h::full_name,
           TIC28X::PushAr1hAr0h::objmode},
          {TIC28X::PushDbgier::opcode, TIC28X::PushDbgier::full_name,
           TIC28X::PushDbgier::objmode},
          {TIC28X::PushDp::opcode, TIC28X::PushDp::full_name,
           TIC28X::PushDp::objmode},
          {TIC28X::PushDpSt1::opcode, TIC28X::PushDpSt1::full_name,
           TIC28X::PushDpSt1::objmode},
          {TIC28X::PushIfr::opcode, TIC28X::PushIfr::full_name,
           TIC28X::PushIfr::objmode},
          {TIC28X::PushLoc16::SetLoc16(TEST_DATA), TIC28X::PushLoc16::full_name,
           TIC28X::PushLoc16::objmode},
          {TIC28X::PushP::opcode, TIC28X::PushP::full_name,
           TIC28X::PushP::objmode},
          {TIC28X::PushRpc::opcode, TIC28X::PushRpc::full_name,
           TIC28X::PushRpc::objmode},
          {TIC28X::PushSt0::opcode, TIC28X::PushSt0::full_name,
           TIC28X::PushSt0::objmode},
          {TIC28X::PushSt1::opcode, TIC28X::PushSt1::full_name,
           TIC28X::PushSt1::objmode},
          {TIC28X::PushTSt0::opcode, TIC28X::PushTSt0::full_name,
           TIC28X::PushTSt0::objmode},
          {TIC28X::PushXt::opcode, TIC28X::PushXt::full_name,
           TIC28X::PushXt::objmode},
          {TIC28X::PwriteXar7Loc16::opcode, TIC28X::PwriteXar7Loc16::full_name,
           TIC28X::PwriteXar7Loc16::objmode},
          {TIC28X::QmaclPLoc32Xar7::SetLoc32(TEST_DATA),
           TIC28X::QmaclPLoc32Xar7::full_name,
           TIC28X::QmaclPLoc32Xar7::objmode},
          {TIC28X::QmaclPLoc32Xar7Postinc::SetLoc32(TEST_DATA),
           TIC28X::QmaclPLoc32Xar7Postinc::full_name,
           TIC28X::QmaclPLoc32Xar7Postinc::objmode},
          {TIC28X::QmpyalPXtLoc32::SetLoc32(TEST_DATA),
           TIC28X::QmpyalPXtLoc32::full_name, TIC28X::QmpyalPXtLoc32::objmode},
          {TIC28X::QmpylPXtLoc32::SetLoc32(TEST_DATA),
           TIC28X::QmpylPXtLoc32::full_name, TIC28X::QmpylPXtLoc32::objmode},
          {TIC28X::QmpylAccXtLoc32::SetLoc32(TEST_DATA),
           TIC28X::QmpylAccXtLoc32::full_name,
           TIC28X::QmpylAccXtLoc32::objmode},
          {TIC28X::QmpyslPXtLoc32::SetLoc32(TEST_DATA),
           TIC28X::QmpyslPXtLoc32::full_name, TIC28X::QmpyslPXtLoc32::objmode},
          {TIC28X::QmpyulPXtLoc32::SetLoc32(TEST_DATA),
           TIC28X::QmpyulPXtLoc32::full_name, TIC28X::QmpyulPXtLoc32::objmode},
          {TIC28X::QmpyxulPXtLoc32::SetLoc32(TEST_DATA),
           TIC28X::QmpyxulPXtLoc32::full_name,
           TIC28X::QmpyxulPXtLoc32::objmode},
          {TIC28X::RolAcc::opcode, TIC28X::RolAcc::full_name,
           TIC28X::RolAcc::objmode},
          {TIC28X::RorAcc::opcode, TIC28X::RorAcc::full_name,
           TIC28X::RorAcc::objmode},
          {TIC28X::RptConst8::SetConst8(TEST_DATA),
           TIC28X::RptConst8::full_name, TIC28X::RptConst8::objmode},
          {TIC28X::RptLoc16::SetLoc16(TEST_DATA), TIC28X::RptLoc16::full_name,
           TIC28X::RptLoc16::objmode},
          {TIC28X::SatAcc::opcode, TIC28X::SatAcc::full_name,
           TIC28X::SatAcc::objmode},
          {TIC28X::Sat64AccP::opcode, TIC28X::Sat64AccP::full_name,
           TIC28X::Sat64AccP::objmode},
          {TIC28X::SbOff8Cond::SetCond(TEST_DATA) |
               TIC28X::SbOff8Cond::SetOff8(TEST_DATA),
           TIC28X::SbOff8Cond::full_name, TIC28X::SbOff8Cond::objmode},
          {TIC28X::SbbuAccLoc16::SetLoc16(TEST_DATA),
           TIC28X::SbbuAccLoc16::full_name, TIC28X::SbbuAccLoc16::objmode},
          {TIC28X::SbfOff8Eq::SetOff8(TEST_DATA), TIC28X::SbfOff8Eq::full_name,
           TIC28X::SbfOff8Eq::objmode},
          {TIC28X::SbfOff8Neq::SetOff8(TEST_DATA),
           TIC28X::SbfOff8Neq::full_name, TIC28X::SbfOff8Neq::objmode},
          {TIC28X::SbfOff8Tc::SetOff8(TEST_DATA), TIC28X::SbfOff8Tc::full_name,
           TIC28X::SbfOff8Tc::objmode},
          {TIC28X::SbfOff8Ntc::SetOff8(TEST_DATA),
           TIC28X::SbfOff8Ntc::full_name, TIC28X::SbfOff8Ntc::objmode},
          {TIC28X::SbrkConst8::SetConst8(TEST_DATA),
           TIC28X::SbrkConst8::full_name, TIC28X::SbrkConst8::objmode},
          {TIC28X::SetcMode::SetMode(TEST_DATA), TIC28X::SetcMode::full_name,
           TIC28X::SetcMode::objmode},
          {TIC28X::SetcM0M1Map::opcode, TIC28X::SetcM0M1Map::full_name,
           TIC28X::SetcM0M1Map::objmode},
          {TIC28X::SetcObjmode::opcode, TIC28X::SetcObjmode::full_name,
           TIC28X::SetcObjmode::objmode},
          {TIC28X::SetcXf::opcode, TIC28X::SetcXf::full_name,
           TIC28X::SetcXf::objmode},
          {TIC28X::SfrAccShift::SetShift(TEST_DATA),
           TIC28X::SfrAccShift::full_name, TIC28X::SfrAccShift::objmode},
          {TIC28X::SfrAccT::opcode, TIC28X::SfrAccT::full_name,
           TIC28X::SfrAccT::objmode},
          {TIC28X::SpmShift::SetPM(TEST_DATA), TIC28X::SpmShift::full_name,
           TIC28X::SpmShift::objmode},
          {TIC28X::SqraLoc16::SetLoc16(TEST_DATA), TIC28X::SqraLoc16::full_name,
           TIC28X::SqraLoc16::objmode},
          {TIC28X::SqrsLoc16::SetLoc16(TEST_DATA), TIC28X::SqrsLoc16::full_name,
           TIC28X::SqrsLoc16::objmode},
          {TIC28X::SubAccLoc16Objmode1::SetLoc16(TEST_DATA),
           TIC28X::SubAccLoc16Objmode1::full_name,
           TIC28X::SubAccLoc16Objmode1::objmode},
          {TIC28X::SubAccLoc16Objmode0::SetLoc16(TEST_DATA),
           TIC28X::SubAccLoc16Objmode0::full_name,
           TIC28X::SubAccLoc16Objmode0::objmode},
          {TIC28X::SubAccLoc16Shift1_15Objmode1::SetLoc16(TEST_DATA) |
               TIC28X::SubAccLoc16Shift1_15Objmode1::SetShift(TEST_DATA),
           TIC28X::SubAccLoc16Shift1_15Objmode1::full_name,
           TIC28X::SubAccLoc16Shift1_15Objmode1::objmode},
          {TIC28X::SubAccLoc16Shift1_15Objmode0::SetLoc16(TEST_DATA) |
               TIC28X::SubAccLoc16Shift1_15Objmode0::SetShift(TEST_DATA),
           TIC28X::SubAccLoc16Shift1_15Objmode0::full_name,
           TIC28X::SubAccLoc16Shift1_15Objmode0::objmode},
          {TIC28X::SubAccLoc16Shift16::SetLoc16(TEST_DATA),
           TIC28X::SubAccLoc16Shift16::full_name,
           TIC28X::SubAccLoc16Shift16::objmode},
          {TIC28X::SubAccLoc16ShiftT::SetLoc16(TEST_DATA),
           TIC28X::SubAccLoc16ShiftT::full_name,
           TIC28X::SubAccLoc16ShiftT::objmode},
          {TIC28X::SubAccConst16Shift::SetConst16(TEST_DATA) |
               TIC28X::SubAccConst16Shift::SetShift(TEST_DATA),
           TIC28X::SubAccConst16Shift::full_name,
           TIC28X::SubAccConst16Shift::objmode},
          {TIC28X::SubAxLoc16::SetLoc16(TEST_DATA) |
               TIC28X::SubAxLoc16::SetRegAx(TEST_DATA),
           TIC28X::SubAxLoc16::full_name, TIC28X::SubAxLoc16::objmode},
          {TIC28X::SubLoc16Ax::SetLoc16(TEST_DATA) |
               TIC28X::SubLoc16Ax::SetRegAx(TEST_DATA),
           TIC28X::SubLoc16Ax::full_name, TIC28X::SubLoc16Ax::objmode},
          {TIC28X::SubbAccConst8::SetConst8(TEST_DATA),
           TIC28X::SubbAccConst8::full_name, TIC28X::SubbAccConst8::objmode},
          {TIC28X::SubbSpConst7::SetConst7(TEST_DATA),
           TIC28X::SubbSpConst7::full_name, TIC28X::SubbSpConst7::objmode},
          {TIC28X::SubbXarnConst7::SetConst7(TEST_DATA) |
               TIC28X::SubbXarnConst7::SetRegN(TEST_DATA),
           TIC28X::SubbXarnConst7::full_name, TIC28X::SubbXarnConst7::objmode},
          {TIC28X::SubblAccLoc32::SetLoc32(TEST_DATA),
           TIC28X::SubblAccLoc32::full_name, TIC28X::SubblAccLoc32::objmode},
          {TIC28X::SubcuAccLoc16::SetLoc16(TEST_DATA),
           TIC28X::SubcuAccLoc16::full_name, TIC28X::SubcuAccLoc16::objmode},
          {TIC28X::SubculAccLoc32::SetLoc32(TEST_DATA),
           TIC28X::SubculAccLoc32::full_name, TIC28X::SubculAccLoc32::objmode},
          {TIC28X::SublAccLoc32::SetLoc32(TEST_DATA),
           TIC28X::SublAccLoc32::full_name, TIC28X::SublAccLoc32::objmode},
          {TIC28X::SublLoc32Acc::SetLoc32(TEST_DATA),
           TIC28X::SublLoc32Acc::full_name, TIC28X::SublLoc32Acc::objmode},
          {TIC28X::SubrLoc16Ax::SetLoc16(TEST_DATA) |
               TIC28X::SubrLoc16Ax::SetRegAx(TEST_DATA),
           TIC28X::SubrLoc16Ax::full_name, TIC28X::SubrLoc16Ax::objmode},
          {TIC28X::SubrlLoc32Acc::SetLoc32(TEST_DATA),
           TIC28X::SubrlLoc32Acc::full_name, TIC28X::SubrlLoc32Acc::objmode},
          {TIC28X::SubuAccLoc16::SetLoc16(TEST_DATA),
           TIC28X::SubuAccLoc16::full_name, TIC28X::SubuAccLoc16::objmode},
          {TIC28X::SubulAccLoc32::SetLoc32(TEST_DATA),
           TIC28X::SubulAccLoc32::full_name, TIC28X::SubulAccLoc32::objmode},
          {TIC28X::SubulPLoc32::SetLoc32(TEST_DATA),
           TIC28X::SubulPLoc32::full_name, TIC28X::SubulPLoc32::objmode},
          {TIC28X::TbitLoc16Bit::SetLoc16(TEST_DATA) |
               TIC28X::TbitLoc16Bit::SetBitIndex(TEST_DATA),
           TIC28X::TbitLoc16Bit::full_name, TIC28X::TbitLoc16Bit::objmode},
          {TIC28X::TbitLoc16T::SetLoc16(TEST_DATA),
           TIC28X::TbitLoc16T::full_name, TIC28X::TbitLoc16T::objmode},
          {TIC28X::TclrLoc16Bit::SetLoc16(TEST_DATA) |
               TIC28X::TclrLoc16Bit::SetBitIndex(TEST_DATA),
           TIC28X::TclrLoc16Bit::full_name, TIC28X::TclrLoc16Bit::objmode},
          {TIC28X::TestAcc::opcode, TIC28X::TestAcc::full_name,
           TIC28X::TestAcc::objmode},
          {TIC28X::TrapVec::SetVec(TEST_DATA), TIC28X::TrapVec::full_name,
           TIC28X::TrapVec::objmode},
          {TIC28X::TsetLoc16Bit::SetLoc16(TEST_DATA) |
               TIC28X::TsetLoc16Bit::SetBitIndex(TEST_DATA),
           TIC28X::TsetLoc16Bit::full_name, TIC28X::TsetLoc16Bit::objmode},
          {TIC28X::UoutPaLoc16::SetLoc16(TEST_DATA) |
               TIC28X::UoutPaLoc16::SetConst16(TEST_DATA),
           TIC28X::UoutPaLoc16::full_name, TIC28X::UoutPaLoc16::objmode},
          {TIC28X::XbAl::opcode, TIC28X::XbAl::full_name,
           TIC28X::XbAl::objmode},
          {TIC28X::XbPmaArpn::SetRegN(TEST_DATA) |
               TIC28X::XbPmaArpn::SetConst16(TEST_DATA),
           TIC28X::XbPmaArpn::full_name, TIC28X::XbPmaArpn::objmode},
          {TIC28X::XbPmaCond::SetCond(TEST_DATA) |
               TIC28X::XbPmaCond::SetConst16(TEST_DATA),
           TIC28X::XbPmaCond::full_name, TIC28X::XbPmaCond::objmode},
          {TIC28X::XbanzPmaInd::SetConst16(TEST_DATA),
           TIC28X::XbanzPmaInd::full_name, TIC28X::XbanzPmaInd::objmode},
          {TIC28X::XbanzPmaIndPostinc::SetConst16(TEST_DATA),
           TIC28X::XbanzPmaIndPostinc::full_name,
           TIC28X::XbanzPmaIndPostinc::objmode},
          {TIC28X::XbanzPmaIndPostdec::SetConst16(TEST_DATA),
           TIC28X::XbanzPmaIndPostdec::full_name,
           TIC28X::XbanzPmaIndPostdec::objmode},
          {TIC28X::XbanzPmaInd0Postinc::SetConst16(TEST_DATA),
           TIC28X::XbanzPmaInd0Postinc::full_name,
           TIC28X::XbanzPmaInd0Postinc::objmode},
          {TIC28X::XbanzPmaInd0Postdec::SetConst16(TEST_DATA),
           TIC28X::XbanzPmaInd0Postdec::full_name,
           TIC28X::XbanzPmaInd0Postdec::objmode},
          {TIC28X::XbanzPmaIndArpn::SetRegN(TEST_DATA) |
               TIC28X::XbanzPmaIndArpn::SetConst16(TEST_DATA),
           TIC28X::XbanzPmaIndArpn::full_name,
           TIC28X::XbanzPmaIndArpn::objmode},
          {TIC28X::XbanzPmaIndPostincArpn::SetRegN(TEST_DATA) |
               TIC28X::XbanzPmaIndPostincArpn::SetConst16(TEST_DATA),
           TIC28X::XbanzPmaIndPostincArpn::full_name,
           TIC28X::XbanzPmaIndPostincArpn::objmode},
          {TIC28X::XbanzPmaIndPostdecArpn::SetRegN(TEST_DATA) |
               TIC28X::XbanzPmaIndPostdecArpn::SetConst16(TEST_DATA),
           TIC28X::XbanzPmaIndPostdecArpn::full_name,
           TIC28X::XbanzPmaIndPostdecArpn::objmode},
          {TIC28X::XbanzPmaInd0PostincArpn::SetRegN(TEST_DATA) |
               TIC28X::XbanzPmaInd0PostincArpn::SetConst16(TEST_DATA),
           TIC28X::XbanzPmaInd0PostincArpn::full_name,
           TIC28X::XbanzPmaInd0PostincArpn::objmode},
          {TIC28X::XbanzPmaInd0PostdecArpn::SetRegN(TEST_DATA) |
               TIC28X::XbanzPmaInd0PostdecArpn::SetConst16(TEST_DATA),
           TIC28X::XbanzPmaInd0PostdecArpn::full_name,
           TIC28X::XbanzPmaInd0PostdecArpn::objmode},
          {TIC28X::XcallAl::opcode, TIC28X::XcallAl::full_name,
           TIC28X::XcallAl::objmode},
          {TIC28X::XcallPmaArpn::SetRegN(TEST_DATA) |
               TIC28X::XcallPmaArpn::SetConst16(TEST_DATA),
           TIC28X::XcallPmaArpn::full_name, TIC28X::XcallPmaArpn::objmode},
          {TIC28X::XcallPmaCond::SetCond(TEST_DATA) |
               TIC28X::XcallPmaCond::SetConst16(TEST_DATA),
           TIC28X::XcallPmaCond::full_name, TIC28X::XcallPmaCond::objmode},
          {TIC28X::XmacPLoc16Pma::SetLoc16(TEST_DATA) |
               TIC28X::XmacPLoc16Pma::SetConst16(TEST_DATA),
           TIC28X::XmacPLoc16Pma::full_name, TIC28X::XmacPLoc16Pma::objmode},
          {TIC28X::XmacdPLoc16Pma::SetLoc16(TEST_DATA) |
               TIC28X::XmacdPLoc16Pma::SetConst16(TEST_DATA),
           TIC28X::XmacdPLoc16Pma::full_name, TIC28X::XmacdPLoc16Pma::objmode},
          {TIC28X::XorAccLoc16::SetLoc16(TEST_DATA),
           TIC28X::XorAccLoc16::full_name, TIC28X::XorAccLoc16::objmode},
          {TIC28X::XorAccConst16Shift0_15::SetShift(TEST_DATA) |
               TIC28X::XorAccConst16Shift0_15::SetConst16(TEST_DATA),
           TIC28X::XorAccConst16Shift0_15::full_name,
           TIC28X::XorAccConst16Shift0_15::objmode},
          {TIC28X::XorAccConst16Shift16::SetConst16(TEST_DATA),
           TIC28X::XorAccConst16Shift16::full_name,
           TIC28X::XorAccConst16Shift16::objmode},
          {TIC28X::XorAxLoc16::SetLoc16(TEST_DATA) |
               TIC28X::XorAxLoc16::SetRegAx(TEST_DATA),
           TIC28X::XorAxLoc16::full_name, TIC28X::XorAxLoc16::objmode},
          {TIC28X::XorLoc16Ax::SetLoc16(TEST_DATA) |
               TIC28X::XorLoc16Ax::SetRegAx(TEST_DATA),
           TIC28X::XorLoc16Ax::full_name, TIC28X::XorLoc16Ax::objmode},
          {TIC28X::XorLoc16Const16::SetLoc16(TEST_DATA) |
               TIC28X::XorLoc16Const16::SetConst16(TEST_DATA),
           TIC28X::XorLoc16Const16::full_name,
           TIC28X::XorLoc16Const16::objmode},
          {TIC28X::XorbAxConst8::SetConst8(TEST_DATA) |
               TIC28X::XorbAxConst8::SetRegAx(TEST_DATA),
           TIC28X::XorbAxConst8::full_name, TIC28X::XorbAxConst8::objmode},
          {TIC28X::XpreadLoc16Pma::SetLoc16(TEST_DATA) |
               TIC28X::XpreadLoc16Pma::SetConst16(TEST_DATA),
           TIC28X::XpreadLoc16Pma::full_name, TIC28X::XpreadLoc16Pma::objmode},
          {TIC28X::XpreadLoc16Al::SetLoc16(TEST_DATA),
           TIC28X::XpreadLoc16Al::full_name, TIC28X::XpreadLoc16Al::objmode},
          {TIC28X::XpwriteAlLoc16::SetLoc16(TEST_DATA),
           TIC28X::XpwriteAlLoc16::full_name, TIC28X::XpwriteAlLoc16::objmode},
          {TIC28X::XretcCond::SetCond(TEST_DATA), TIC28X::XretcCond::full_name,
           TIC28X::XretcCond::objmode},
          {TIC28X::ZalrAccLoc16::SetLoc16(TEST_DATA),
           TIC28X::ZalrAccLoc16::full_name, TIC28X::ZalrAccLoc16::objmode},
          {TIC28X::Zapa::opcode, TIC28X::Zapa::full_name,
           TIC28X::Zapa::objmode},

          /* Extended Instruction Set */

          // FPU Instructions

          {TIC28X::Absf32RahRbh::SetRegA(TEST_DATA) |
               TIC28X::Absf32RahRbh::SetRegB(TEST_DATA),
           TIC28X::Absf32RahRbh::full_name, TIC28X::Absf32RahRbh::objmode},
          {TIC28X::Addf32Rah16fhiRbh::SetRegA(TEST_DATA) |
               TIC28X::Addf32Rah16fhiRbh::SetRegB(TEST_DATA) |
               TIC28X::Addf32Rah16fhiRbh::Set16fhi(TEST_DATA),
           TIC28X::Addf32Rah16fhiRbh::full_name,
           TIC28X::Addf32Rah16fhiRbh::objmode},
          {TIC28X::Addf32RahRbhRch::SetRegA(TEST_DATA) |
               TIC28X::Addf32RahRbhRch::SetRegB(TEST_DATA) |
               TIC28X::Addf32RahRbhRch::SetRegC(TEST_DATA),
           TIC28X::Addf32RahRbhRch::full_name,
           TIC28X::Addf32RahRbhRch::objmode},
          {TIC28X::Addf32RdhRehRfhMov32Mem32Rah::SetRegA(TEST_DATA) |
               TIC28X::Addf32RdhRehRfhMov32Mem32Rah::SetRegD(TEST_DATA) |
               TIC28X::Addf32RdhRehRfhMov32Mem32Rah::SetRegE(TEST_DATA) |
               TIC28X::Addf32RdhRehRfhMov32Mem32Rah::SetRegF(TEST_DATA) |
               TIC28X::Addf32RdhRehRfhMov32Mem32Rah::SetMem32(TEST_DATA),
           TIC28X::Addf32RdhRehRfhMov32Mem32Rah::full_name,
           TIC28X::Addf32RdhRehRfhMov32Mem32Rah::objmode},
          {TIC28X::Addf32RdhRehRfhMov32RahMem32::SetRegA(TEST_DATA) |
               TIC28X::Addf32RdhRehRfhMov32RahMem32::SetRegD(TEST_DATA) |
               TIC28X::Addf32RdhRehRfhMov32RahMem32::SetRegE(TEST_DATA) |
               TIC28X::Addf32RdhRehRfhMov32RahMem32::SetRegF(TEST_DATA) |
               TIC28X::Addf32RdhRehRfhMov32RahMem32::SetMem32(TEST_DATA),
           TIC28X::Addf32RdhRehRfhMov32RahMem32::full_name,
           TIC28X::Addf32RdhRehRfhMov32RahMem32::objmode},
          {TIC28X::Cmpf32RahRbh::SetRegA(TEST_DATA) |
               TIC28X::Cmpf32RahRbh::SetRegB(TEST_DATA),
           TIC28X::Cmpf32RahRbh::full_name, TIC28X::Cmpf32RahRbh::objmode},
          {TIC28X::Cmpf32Rah16fhi::SetRegA(TEST_DATA) |
               TIC28X::Cmpf32Rah16fhi::Set16fhi(TEST_DATA),
           TIC28X::Cmpf32Rah16fhi::full_name, TIC28X::Cmpf32Rah16fhi::objmode},
          {TIC28X::Cmpf32Rah0::SetRegA(TEST_DATA),
           TIC28X::Cmpf32Rah0::full_name, TIC28X::Cmpf32Rah0::objmode},
          {TIC28X::Einvf32RahRbh::SetRegA(TEST_DATA) |
               TIC28X::Einvf32RahRbh::SetRegB(TEST_DATA),
           TIC28X::Einvf32RahRbh::full_name, TIC28X::Einvf32RahRbh::objmode},
          {TIC28X::Eisqrtf32RahRbh::SetRegA(TEST_DATA) |
               TIC28X::Eisqrtf32RahRbh::SetRegB(TEST_DATA),
           TIC28X::Eisqrtf32RahRbh::full_name,
           TIC28X::Eisqrtf32RahRbh::objmode},
          {TIC28X::F32toi16RahRbh::SetRegA(TEST_DATA) |
               TIC28X::F32toi16RahRbh::SetRegB(TEST_DATA),
           TIC28X::F32toi16RahRbh::full_name, TIC28X::F32toi16RahRbh::objmode},
          {TIC28X::F32toi16rRahRbh::SetRegA(TEST_DATA) |
               TIC28X::F32toi16rRahRbh::SetRegB(TEST_DATA),
           TIC28X::F32toi16rRahRbh::full_name,
           TIC28X::F32toi16rRahRbh::objmode},
          {TIC28X::F32toi32RahRbh::SetRegA(TEST_DATA) |
               TIC28X::F32toi32RahRbh::SetRegB(TEST_DATA),
           TIC28X::F32toi32RahRbh::full_name, TIC28X::F32toi32RahRbh::objmode},
          {TIC28X::F32toui16RahRbh::SetRegA(TEST_DATA) |
               TIC28X::F32toui16RahRbh::SetRegB(TEST_DATA),
           TIC28X::F32toui16RahRbh::full_name,
           TIC28X::F32toui16RahRbh::objmode},
          {TIC28X::F32toui16rRahRbh::SetRegA(TEST_DATA) |
               TIC28X::F32toui16rRahRbh::SetRegB(TEST_DATA),
           TIC28X::F32toui16rRahRbh::full_name,
           TIC28X::F32toui16rRahRbh::objmode},
          {TIC28X::F32toui32RahRbh::SetRegA(TEST_DATA) |
               TIC28X::F32toui32RahRbh::SetRegB(TEST_DATA),
           TIC28X::F32toui32RahRbh::full_name,
           TIC28X::F32toui32RahRbh::objmode},
          {TIC28X::Fracf32RahRbh::SetRegA(TEST_DATA) |
               TIC28X::Fracf32RahRbh::SetRegB(TEST_DATA),
           TIC28X::Fracf32RahRbh::full_name, TIC28X::Fracf32RahRbh::objmode},
          {TIC28X::I16tof32RahRbh::SetRegA(TEST_DATA) |
               TIC28X::I16tof32RahRbh::SetRegB(TEST_DATA),
           TIC28X::I16tof32RahRbh::full_name, TIC28X::I16tof32RahRbh::objmode},
          {TIC28X::I16tof32RahMem16::SetRegA(TEST_DATA) |
               TIC28X::I16tof32RahMem16::SetMem16(TEST_DATA),
           TIC28X::I16tof32RahMem16::full_name,
           TIC28X::I16tof32RahMem16::objmode},
          {TIC28X::I32tof32RahMem32::SetRegA(TEST_DATA) |
               TIC28X::I32tof32RahMem32::SetMem32(TEST_DATA),
           TIC28X::I32tof32RahMem32::full_name,
           TIC28X::I32tof32RahMem32::objmode},
          {TIC28X::I32tof32RahRbh::SetRegA(TEST_DATA) |
               TIC28X::I32tof32RahRbh::SetRegB(TEST_DATA),
           TIC28X::I32tof32RahRbh::full_name, TIC28X::I32tof32RahRbh::objmode},
          {TIC28X::Macf32R3hR2hRdhRehRfh::SetRegD(TEST_DATA) |
               TIC28X::Macf32R3hR2hRdhRehRfh::SetRegE(TEST_DATA) |
               TIC28X::Macf32R3hR2hRdhRehRfh::SetRegF(TEST_DATA),
           TIC28X::Macf32R3hR2hRdhRehRfh::full_name,
           TIC28X::Macf32R3hR2hRdhRehRfh::objmode},
          {TIC28X::Macf32R3hR2hRdhRehRfhMov32RahMem32::SetRegA(TEST_DATA) |
               TIC28X::Macf32R3hR2hRdhRehRfhMov32RahMem32::SetRegD(TEST_DATA) |
               TIC28X::Macf32R3hR2hRdhRehRfhMov32RahMem32::SetRegE(TEST_DATA) |
               TIC28X::Macf32R3hR2hRdhRehRfhMov32RahMem32::SetRegF(TEST_DATA) |
               TIC28X::Macf32R3hR2hRdhRehRfhMov32RahMem32::SetMem32(TEST_DATA),
           TIC28X::Macf32R3hR2hRdhRehRfhMov32RahMem32::full_name,
           TIC28X::Macf32R3hR2hRdhRehRfhMov32RahMem32::objmode},
          {TIC28X::Macf32R7hR3hMem32Xar7Postinc::SetMem32(TEST_DATA),
           TIC28X::Macf32R7hR3hMem32Xar7Postinc::full_name,
           TIC28X::Macf32R7hR3hMem32Xar7Postinc::objmode},
          {TIC28X::Macf32R7hR6hRdhRehRfh::SetRegD(TEST_DATA) |
               TIC28X::Macf32R7hR6hRdhRehRfh::SetRegE(TEST_DATA) |
               TIC28X::Macf32R7hR6hRdhRehRfh::SetRegF(TEST_DATA),
           TIC28X::Macf32R7hR6hRdhRehRfh::full_name,
           TIC28X::Macf32R7hR6hRdhRehRfh::objmode},
          {TIC28X::Macf32R7hR6hRdhRehRfhMov32RahMem32::SetRegA(TEST_DATA) |
               TIC28X::Macf32R7hR6hRdhRehRfhMov32RahMem32::SetRegD(TEST_DATA) |
               TIC28X::Macf32R7hR6hRdhRehRfhMov32RahMem32::SetRegE(TEST_DATA) |
               TIC28X::Macf32R7hR6hRdhRehRfhMov32RahMem32::SetRegF(TEST_DATA) |
               TIC28X::Macf32R7hR6hRdhRehRfhMov32RahMem32::SetMem32(TEST_DATA),
           TIC28X::Macf32R7hR6hRdhRehRfhMov32RahMem32::full_name,
           TIC28X::Macf32R7hR6hRdhRehRfhMov32RahMem32::objmode},
          {TIC28X::Maxf32RahRbh::SetRegA(TEST_DATA) |
               TIC28X::Maxf32RahRbh::SetRegB(TEST_DATA),
           TIC28X::Maxf32RahRbh::full_name, TIC28X::Maxf32RahRbh::objmode},
          {TIC28X::Maxf32Rah16fhi::SetRegA(TEST_DATA) |
               TIC28X::Maxf32Rah16fhi::Set16fhi(TEST_DATA),
           TIC28X::Maxf32Rah16fhi::full_name, TIC28X::Maxf32Rah16fhi::objmode},
          {TIC28X::Maxf32RahRbhMov32RchRdh::SetRegA(TEST_DATA) |
               TIC28X::Maxf32RahRbhMov32RchRdh::SetRegB(TEST_DATA) |
               TIC28X::Maxf32RahRbhMov32RchRdh::SetRegC(TEST_DATA) |
               TIC28X::Maxf32RahRbhMov32RchRdh::SetRegD(TEST_DATA),
           TIC28X::Maxf32RahRbhMov32RchRdh::full_name,
           TIC28X::Maxf32RahRbhMov32RchRdh::objmode},
          {TIC28X::Minf32RahRbh::SetRegA(TEST_DATA) |
               TIC28X::Minf32RahRbh::SetRegB(TEST_DATA),
           TIC28X::Minf32RahRbh::full_name, TIC28X::Minf32RahRbh::objmode},
          {TIC28X::Minf32Rah16fhi::SetRegA(TEST_DATA) |
               TIC28X::Minf32Rah16fhi::Set16fhi(TEST_DATA),
           TIC28X::Minf32Rah16fhi::full_name, TIC28X::Minf32Rah16fhi::objmode},
          {TIC28X::Minf32RahRbhMov32RchRdh::SetRegA(TEST_DATA) |
               TIC28X::Minf32RahRbhMov32RchRdh::SetRegB(TEST_DATA) |
               TIC28X::Minf32RahRbhMov32RchRdh::SetRegC(TEST_DATA) |
               TIC28X::Minf32RahRbhMov32RchRdh::SetRegD(TEST_DATA),
           TIC28X::Minf32RahRbhMov32RchRdh::full_name,
           TIC28X::Minf32RahRbhMov32RchRdh::objmode},

      };

  return opcodes;
}

class TestDecodeInstructions
    : public ::testing::TestWithParam<
          std::tuple<unsigned int, std::string, TIC28X::ObjectMode>> {};

TEST_P(TestDecodeInstructions, TestDecode) {
  const uint32_t opcode = std::get<0>(GetParam());
  const std::string want = std::get<1>(GetParam());
  const TIC28X::ObjectMode objmode = std::get<2>(GetParam());
  std::array<uint8_t, 4> full_op = {};

  // Build full opcode in little endian according to 2 or 4 bytes
  if ((opcode & 0xFFFF0000) == 0) {  // 2 byte opcode
    full_op = {
        static_cast<uint8_t>(opcode & 0xFF),
        static_cast<uint8_t>((opcode & 0xFF00) >> 8),
        0,
        0,
    };
  } else {  // 4-byte opcode
    full_op = {
        static_cast<uint8_t>((opcode & 0xFF0000) >> 16),
        static_cast<uint8_t>((opcode & 0xFF000000) >> 24),
        static_cast<uint8_t>(opcode & 0xFF),
        static_cast<uint8_t>((opcode & 0xFF00) >> 8),
    };
  }

  const auto instructions = TIC28X::GenerateInstructionVector();
  const auto i =
      TIC28X::DecodeInstruction(full_op.data(), instructions, objmode);

  if (want == "NULLOPT") {
    EXPECT_EQ(std::nullopt, i);
  } else {
    EXPECT_NE(i, std::nullopt);  // guard against segfault
    EXPECT_EQ(want, i->get()->GetFullName());
  }
}

INSTANTIATE_TEST_SUITE_P(
    TestAll, TestDecodeInstructions, ::testing::ValuesIn(GenerateTestOpcodes()),
    [](const testing::TestParamInfo<TestDecodeInstructions::ParamType>& info) {
      auto op = std::get<0>(info.param);
      auto want = std::get<1>(info.param);

      std::stringstream ss;
      ss << std::hex << op;
      const std::string hex_str = ss.str();

      return "OP_" + hex_str + "_" + want;
    });
